version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: coupon_recommendation_system
      POSTGRES_PASSWORD: Xq8@SHF0S1&sM7v3
      POSTGRES_DB: betting_recommendation_system
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  kafka:
#    image: ubuntu/kafka:latest
#    restart: always
#    ports:
#      - '9092:9092'
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ADVERTISED_PORT: 9092
  app:
    build: .
    restart: always
    stop_signal: SIGINT
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: coupon_recommendation_system
      POSTGRES_PASSWORD: Xq8@SHF0S1&sM7v3
      POSTGRES_DB: betting_recommendation_system
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
