---
- name: install apache2
  hosts: all
  become: true  # change user, if not specify you change to root.
  tasks:

    - name: install apache2 package
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: ensure apache2 service started
      service:
        name: apache2
        state: started
        enabled: yes

    - name: create /app directory
      file:
        path: /app
        state: directory
        mode: 0755

    - name: copy files to remote
      copy:
        src: ../../.*
        dest: /app # This doesn't create directories, you have to do a task before to make it
        mode: 0755 # permissions mode